name: Tasmota CI

on:
  pull_request:

jobs:
  tasmota:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-minimal
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-lite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-lite
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-knx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-knx
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-sensors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-sensors
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-display:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-display
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-ir:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-ir
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-zbbridge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-zbbridge
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-zigbee:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-zigbee
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-AF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-AF
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-BG:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-BG
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-BR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-BR
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-CN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-CN
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-CZ:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-CZ
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-DE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-DE
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-ES:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-ES
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-FR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-FR
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-FY:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-FY
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-GR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-GR
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-HE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-HE
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-HU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-HU
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-IT:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-IT
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-KO:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-KO
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-NL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-NL
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-PL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-PL
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-PT:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-PT
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-RO:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-RO
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-RU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-RU
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-SE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-SE
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-SK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-SK
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-TR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-TR
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-TW:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-TW
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-UK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-UK
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-VN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-VN
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output
