name: "Mark or close stale issues and PRs"
 
on:
  schedule:
  - cron: "30 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.15
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 25
        days-before-close: 5
        stale-issue-message: "This issue has been automatically marked as stale because it hasn't any activity in last few weeks. It will be closed if no further activity occurs. Thank you for your contributions."
        stale-pr-message: "This PR has been automatically marked as stale because it hasn't any activity in last few weeks. It will be closed if no further activity occurs. Thank you for your contributions."
        close-issue-message: "This issue was automatically closed because of being stale. Feel free to open a new one if you still experience this problem."
        close-pr-message: "This PR was automatically closed because of being stale."
        stale-pr-label: "stale"
        stale-issue-label: "stale"
        exempt-issue-labels: "bug,enhancement,pinned,security"
        exempt-pr-labels: "bug,enhancement,pinned,security"
